pipeline:
  build:
    image: node:8
    environment:
      - NODE_ENV=test
      - PM2_HOME=/tmp
    commands:
      - node -v
      - yarn -v
      - uname -r
      - yarn install 2> /dev/null
      - export PATH=$PATH:./node_modules/.bin/
      - nyc -s --clean false mocha test/units/InteractorClient.mocha.js
      - nyc -s --clean false mocha test/units/InteractorDaemon.mocha.js
      - nyc -s --clean false mocha test/units/PM2Client.mocha.js
      - nyc -s --clean false mocha test/units/Utility/stacktrace.mocha.js
      - nyc -s --clean false mocha test/units/Utility/cache.mocha.js
      - nyc -s --clean false mocha test/units/WatchDog.mocha.js
      - nyc -s --clean false mocha test/units/push/PushInteractor.mocha.js
      - nyc -s --clean false mocha test/units/push/TransactionAggregator.mocha.js
      - nyc -s --clean false mocha test/units/reverse/ReverseInteractor.mocha.js
      - nyc -s --clean false mocha test/units/transporters/AxonTransport.mocha.js
      - nyc -s --clean false mocha test/units/transporters/WebsocketTransport.mocha.js
      - nyc -s --clean false mocha test/units/TransporterInterface.mocha.js
      - nyc -s --clean false mocha test/units/PM2Interface.mocha.js
      - nyc -s --clean false mocha test/integrations/websocket.mocha.js
      - nyc -s --clean false mocha test/integrations/axon.mocha.js
      - yarn add codecov
      - nyc report --reporter=text-lcov > coverage.lcov
      - codecov -t $${CODECOV_TOKEN}
    secrets: [ codecov_token ]
    when:
      event: push
  slack:
    image: plugins/slack
    channel: ci 
    status: [ success, failure ]
    template: |
      {{#success build.status}}
        {{repo.name}} : {{build.event}} with commit {{truncate build.commit 8}} on branch "{{build.branch}}" done by {{build.author}} succeeded in {{since build.started}}
      {{else}}
        {{repo.name}} : {{build.event}} with commit {{truncate build.commit 8}} on branch "{{build.branch}}" done by {{build.author}} failed in {{since build.started}}
      {{/success}}
      see {{ build.link }}
    secrets: [ slack_webhook ]