pipeline:
  build:
    image: node:${NODE_VERSION}
    environment:
      - NODE_ENV=test
      - PM2_HOME=/tmp
    commands:
      - node -v
      - yarn -v
      - uname -r
      - yarn install 2> /dev/null
      - export PATH=$PATH:./node_modules/.bin/
      - mocha test/units/InteractorClient.mocha.js
      - mocha test/units/InteractorDaemon.mocha.js
      - mocha test/units/PM2Client.mocha.js
      - mocha test/units/Utility/stacktrace.mocha.js
      - mocha test/units/Utility/cache.mocha.js
      - mocha test/units/WatchDog.mocha.js
      - mocha test/units/push/PushInteractor.mocha.js
      - mocha test/units/push/TransactionAggregator.mocha.js
      - mocha test/units/reverse/ReverseInteractor.mocha.js
      - mocha test/units/transporters/AxonTransport.mocha.js
      - mocha test/units/transporters/WebsocketTransport.mocha.js
      - mocha test/units/TransporterInterface.mocha.js
      - mocha test/units/PM2Interface.mocha.js
      - mocha test/integrations/websocket.mocha.js
      - mocha test/integrations/axon.mocha.js
    secrets: [ codecov_token ]
    when:
      event: push
  slack:
    image: plugins/slack
    channel: ci 
    status: [ success, failure ]
    template: |
      {{#success build.status}}
        {{repo.name}} : {{build.event}} with commit {{truncate build.commit 8}} on branch "{{build.branch}}" with node:${NODE_VERSION} done by {{build.author}} succeeded in {{since build.started}}
      {{else}}
        {{repo.name}} : {{build.event}} with commit {{truncate build.commit 8}} on branch "{{build.branch}}" with node:${NODE_VERSION} done by {{build.author}} failed in {{since build.started}}
      {{/success}}
      see {{ build.link }}
    secrets: [ slack_webhook ]
    when:
      event: push
  publish_npm:
    image: plugins/npm
    secrets: [ npm_username, npm_password, npm_email ]
    when:
      event: [ tag ]
matrix:
  NODE_VERSION:
    - 4
    - 6
    - 7
    - 8