name: Node.js CI

on: [push, pull_request]

jobs:

  node-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create .pm2 directory
      run: mkdir -p ~/.pm2
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm run test
